<a href="https://colab.research.google.com/github/Vedansh5674/data-analytics-task-python-Jupyter-Notebook/blob/main/Level_1_Task_2_City_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

df = pd.read_csv("Dataset .csv")

# Count restaurants per city
city_counts = df['City'].value_counts()

# City with highest number of restaurants
top_city = city_counts.idxmax()
top_count = city_counts.max()

print("City with most restaurants:", top_city)
print("Number of restaurants:", top_count)

City with most restaurants: New Delhi
Number of restaurants: 5473

In [7]:
avg_rating = df.groupby('City')['Aggregate rating'].mean()

print(avg_rating)

City
Abu Dhabi          4.300000
Agra               3.965000
Ahmedabad          4.161905
Albany             3.555000
Allahabad          3.395000
                     ...
Weirton            3.900000
Wellington City    4.250000
Winchester Bay     3.200000
Yorkton            3.300000
��stanbul          4.292857
Name: Aggregate rating, Length: 141, dtype: float64

In [8]:
best_city = avg_rating.idxmax()
best_rating = avg_rating.max()

print("City with highest average rating:", best_city)
print("Average rating:", best_rating)

City with highest average rating: Inner City
Average rating: 4.9

In [11]:
import pandas as pd

df = pd.read_csv("Dataset .csv")

# 1. Most restaurants
city_counts = df['City'].value_counts()
print("Most restaurants:", city_counts.idxmax())

# 2. Average rating per city
avg_rating = df.groupby('City')['Aggregate rating'].mean()

# 3. Best rated city
print("Highest avg rating city:", avg_rating.idxmax())

Most restaurants: New Delhi
Highest avg rating city: Inner City

In [12]:
top_5_cities = city_counts.head(5)
print(top_5_cities)

City
New Delhi    5473
Gurgaon      1118
Noida        1080
Faridabad     251
Ghaziabad      25
Name: count, dtype: int64

In [13]:
top_5_rated_cities = avg_rating.sort_values(ascending=False).head(5)
print(top_5_rated_cities)

City
Inner City          4.900000
Quezon City         4.800000
Makati City         4.650000
Pasig City          4.633333
Mandaluyong City    4.625000
Name: Aggregate rating, dtype: float64

In [15]:
df = df.dropna(subset=['City', 'Aggregate rating'])

In [24]:
df['Aggregate rating'] = df['Aggregate rating'].fillna(df['Aggregate rating'].mean())

In [17]:
correlation = df['Aggregate rating'].corr(df['Votes'])
print(f"Correlation between 'Aggregate rating' and 'Votes': {correlation:.2f}")

Correlation between 'Aggregate rating' and 'Votes': 0.31

In [19]:
summary = df.groupby('City').agg(
    total_restaurants=('Restaurant Name', 'count'),
    avg_rating=('Aggregate rating', 'mean')
)

print(summary.sort_values(by='avg_rating', ascending=False).head())

                  total_restaurants  avg_rating
City
Inner City                        2    4.900000
Quezon City                       1    4.800000
Makati City                       2    4.650000
Pasig City                        3    4.633333
Mandaluyong City                  4    4.625000

In [20]:
summary['score'] = summary['total_restaurants'] * summary['avg_rating']
best_city = summary['score'].idxmax()

print("Best overall city:", best_city)

Best overall city: New Delhi

In [21]:
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

,Restaurant ID,Country Code,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
count,9.551000e+03,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000
mean,9.051128e+06,18.365616,64.126574,25.854381,1199.210763,1.804837,2.666370,156.909748
std,8.791521e+06,56.750546,41.467058,11.007935,16121.183073,0.905609,1.516378,430.169145
min,5.300000e+01,1.000000,-157.948486,-41.330428,0.000000,1.000000,0.000000,0.000000
25%,3.019625e+05,1.000000,77.081343,28.478713,250.000000,1.000000,2.500000,5.000000
50%,6.004089e+06,1.000000,77.191964,28.570469,400.000000,2.000000,3.200000,31.000000
75%,1.835229e+07,1.000000,77.282006,28.642758,700.000000,2.000000,3.700000,131.000000
max,1.850065e+07,216.000000,174.832089,55.976980,800000.000000,4.000000,4.900000,10934.000000

In [22]:
df = df.drop_duplicates()

In [29]:
df = df[(df['Aggregate rating'] >= 0) & (df['Aggregate rating'] <= 5)]

In [27]:
avg_rating.sort_values(ascending=False)
city_counts.sort_values(ascending=False)

City
New Delhi         5473
Gurgaon           1118
Noida             1080
Faridabad          251
Ghaziabad           25
                  ...
Lakes Entrance       1
Mohali               1
Panchkula            1
Bandung              1
Randburg             1
Name: count, Length: 141, dtype: int64